"""DrinkReminder backend — FastAPI + SQLAlchemy + SQLite.

Anonymous device-scoped storage: the device UUID generated by the app is the
identifier (sent as the X-Device-Id header or a device_id query/body field).
No accounts, no auth tokens. The backend is a backup layer; the app works
fully offline without it.

Run:  uvicorn main:app --host 0.0.0.0 --port 8000
"""

from datetime import datetime, time
from typing import Optional

from fastapi import Depends, FastAPI, Header, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy import select
from sqlalchemy.orm import Session

import models
import schemas
from database import Base, engine, get_db

Base.metadata.create_all(bind=engine)

app = FastAPI(
    title="DrinkReminder API",
    description="Anonymous, device-scoped backup storage for the DrinkReminder app.",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


def resolve_device_id(
    x_device_id: Optional[str] = Header(default=None, alias="X-Device-Id"),
    device_id: Optional[str] = Query(default=None),
) -> str:
    resolved = x_device_id or device_id
    if not resolved:
        raise HTTPException(
            status_code=400,
            detail="Provide the device id via the X-Device-Id header or device_id query param",
        )
    return resolved


def get_or_create_device(db: Session, device_id: str) -> models.Device:
    device = db.get(models.Device, device_id)
    if device is None:
        device = models.Device(device_id=device_id)
        db.add(device)
        db.commit()
        db.refresh(device)
    return device


def parse_range_bound(value: Optional[str], *, end: bool) -> Optional[datetime]:
    """Accept 'YYYY-MM-DD' or a full ISO datetime; date-only 'to' extends to end of day."""
    if not value:
        return None
    try:
        if len(value) == 10:
            day = datetime.fromisoformat(value)
            return datetime.combine(day.date(), time.max) if end else day
        return datetime.fromisoformat(value)
    except ValueError:
        raise HTTPException(status_code=422, detail=f"Invalid datetime: {value!r}")


@app.get("/health")
def health() -> dict:
    return {"status": "ok"}


@app.post("/devices/register", response_model=schemas.DeviceOut)
def register_device(
    payload: Optional[schemas.DeviceRegisterIn] = None,
    x_device_id: Optional[str] = Header(default=None, alias="X-Device-Id"),
    db: Session = Depends(get_db),
) -> models.Device:
    """Idempotent: creates the device row if it does not exist yet."""
    device_id = (payload.device_id if payload else None) or x_device_id
    if not device_id:
        raise HTTPException(status_code=400, detail="device_id is required")
    return get_or_create_device(db, device_id)


@app.get("/entries", response_model=list[schemas.EntryOut])
def list_entries(
    device_id: str = Depends(resolve_device_id),
    from_: Optional[str] = Query(default=None, alias="from"),
    to: Optional[str] = Query(default=None),
    db: Session = Depends(get_db),
) -> list[models.IntakeEntry]:
    query = select(models.IntakeEntry).where(models.IntakeEntry.device_id == device_id)
    start = parse_range_bound(from_, end=False)
    finish = parse_range_bound(to, end=True)
    if start is not None:
        query = query.where(models.IntakeEntry.created_at >= start)
    if finish is not None:
        query = query.where(models.IntakeEntry.created_at <= finish)
    query = query.order_by(models.IntakeEntry.created_at.asc(), models.IntakeEntry.id.asc())
    return list(db.scalars(query))


@app.post("/entries", response_model=schemas.EntryOut, status_code=201)
def create_entry(payload: schemas.EntryCreate, db: Session = Depends(get_db)) -> models.IntakeEntry:
    get_or_create_device(db, payload.device_id)
    entry = models.IntakeEntry(
        device_id=payload.device_id,
        amount_ml=payload.amount_ml,
        container_type=payload.container_type,
        created_at=payload.created_at,
    )
    db.add(entry)
    db.commit()
    db.refresh(entry)
    return entry


@app.delete("/entries/{entry_id}", status_code=204)
def delete_entry(
    entry_id: int,
    device_id: str = Depends(resolve_device_id),
    db: Session = Depends(get_db),
) -> None:
    entry = db.get(models.IntakeEntry, entry_id)
    if entry is None or entry.device_id != device_id:
        raise HTTPException(status_code=404, detail="Entry not found")
    db.delete(entry)
    db.commit()


@app.get("/settings", response_model=schemas.SettingsOut)
def get_settings(
    device_id: str = Depends(resolve_device_id),
    db: Session = Depends(get_db),
) -> models.UserSettings:
    get_or_create_device(db, device_id)
    settings = db.get(models.UserSettings, device_id)
    if settings is None:
        settings = models.UserSettings(device_id=device_id)
        db.add(settings)
        db.commit()
        db.refresh(settings)
    return settings


@app.put("/settings", response_model=schemas.SettingsOut)
def put_settings(payload: schemas.SettingsIn, db: Session = Depends(get_db)) -> models.UserSettings:
    get_or_create_device(db, payload.device_id)
    settings = db.get(models.UserSettings, payload.device_id)
    if settings is None:
        settings = models.UserSettings(device_id=payload.device_id)
        db.add(settings)
    settings.daily_goal_ml = payload.daily_goal_ml
    settings.weight_kg = payload.weight_kg
    settings.unit = payload.unit
    settings.theme_color = payload.theme_color
    settings.container_icon = payload.container_icon
    db.commit()
    db.refresh(settings)
    return settings
